openapi: "3.0.2"
info:
  title: web3rpc
  version: "0.9.0"
  contact:
    name: API support
    url: https://forum.klaytn.foundation/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
x-tagGroups:
  - name: namespaces
    tags:
      - subbridge
servers:
  - url: http://localhost:8551
  - url: https://api.baobab.klaytn.net:8651
  - url: https://public-en-cypress.klaytn.net
paths:

  # subbridge:
  /subbridge/addPeer:
    $ref: ../../web3rpc/rpc-specs/paths/subbridge/addPeer.yaml#/paths/~1subbridge~1addPeer
  /subbridge/anchoring:
    $ref: ../../web3rpc/rpc-specs/paths/subbridge/anchoring.yaml#/paths/~1subbridge~1anchoring
  /subbridge/convertRequestTxHashToHandleTxHash:
    $ref: ../../web3rpc/rpc-specs/paths/subbridge/convertRequestTxHashToHandleTxHash.yaml#/paths/~1subbridge~1convertRequestTxHashToHandleTxHash  
  /subbridge/deployBridge:
    $ref: ../../web3rpc/rpc-specs/paths/subbridge/deployBridge.yaml#/paths/~1subbridge~1deployBridge
  /subbridge/deregisterBridge:
    $ref: ../../web3rpc/rpc-specs/paths/subbridge/deregisterBridge.yaml#/paths/~1subbridge~1deregisterBridge
  /subbridge/deregisterToken:
    $ref: ../../web3rpc/rpc-specs/paths/subbridge/deregisterToken.yaml#/paths/~1subbridge~1deregisterToken
  /subbridge/getBridgeInFormation:
    $ref: ../../web3rpc/rpc-specs/paths/subbridge/getBridgeInformation.yaml#/paths/~1subbridge~1getBridgeInformation
  /subbridge/getReceiptFromParentChain:
    $ref: ../../web3rpc/rpc-specs/paths/subbridge/getReceiptFromParentChain.yaml#/paths/~1subbridge~1getReceiptFromParentChain
  /subbridge/listBridge:
    $ref: ../../web3rpc/rpc-specs/paths/subbridge/listBridge.yaml#/paths/~1subbridge~1listBridge
  /subbridge/nodeInfo:
    $ref: ../../web3rpc/rpc-specs/paths/subbridge/nodeInfo.yaml#/paths/~1subbridge~1nodeInfo
  /subbridge/registerBridge:
    $ref: ../../web3rpc/rpc-specs/paths/subbridge/registerBridge.yaml#/paths/~1subbridge~1registerBridge
  /subbridge/registerToken:
    $ref: ../../web3rpc/rpc-specs/paths/subbridge/registerToken.yaml#/paths/~1subbridge~1registerToken
  /subbridge/removePeer:
    $ref: ../../web3rpc/rpc-specs/paths/subbridge/removePeer.yaml#/paths/~1subbridge~1removePeer
  /subbridge/subscribeBridge:
    $ref: ../../web3rpc/rpc-specs/paths/subbridge/subscribeBridge.yaml#/paths/~1subbridge~1subscribeBridge
  /subbridge/txPending:
    $ref: ../../web3rpc/rpc-specs/paths/subbridge/txPending.yaml#/paths/~1subbridge~1txPending
  /subbridge/txPendingCount:
    $ref: ../../web3rpc/rpc-specs/paths/subbridge/txPendingCount.yaml#/paths/~1subbridge~1txPendingCount
  /subbridge/unsubscribeBridge:
    $ref: ../../web3rpc/rpc-specs/paths/subbridge/unsubscribeBridge.yaml#/paths/~1subbridge~1unsubscribeBridge