openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /debug/seedHash:
    post:
      operationId: seedHash
      summary: "[Inspection] debug_seedHash"
      description: |
        Retrieves the seed hash of a block.

        **JSONRPC:** `debug_seedHash`
      tags:
        - debug

      parameters:
        - name: blockNumber
          required: true
          schema:
            type: integer
            format: uint64
          description: The block number.
          in: query

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/SeedHashReq"

      responses:
        200:
          description: The block seed hash.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        title: SeedHash
                        type: string
                        description: The block seed hash.
                        example: "0x0000000000000000000000000000000000000000000000000000000000000000"


      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/debug/others/seedHash.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        # - lang: "javascript"
        #   label: "Javascript"
        #   source:
        #     $ref: "../../../code-samples/javascript/debug/others/seedHash.js"
        # - lang: "python"
        #   label: "Python"
        #   source:
        #     $ref: ""

components:
  schemas:
    SeedHashReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'debug_seedHash'
        params:
          type: array
          items:
            type: integer
            format: uint64
          description: The block number.
          example: [100]