openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /debug/freeOSMemory:
    post:
      operationId: freeOSMemory
      summary: "[runtimeDebug] debug_freeOSMemory"
      description: |
        Returns unused memory to the OS.
        
        **JSONRPC:** `debug_freeOSMemory`

      tags:
        - debug

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/FreeOSMemoryReq"

      responses:
        200:
          description: Returns value null
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/FreeOSMemoryResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/debug/runtimeDebugging/freeOSMemory.sh"
        - lang: "java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/debug/runtimeDebugging/DebugFreeOSMemoryExample.java"
        - lang: "javascript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/debug/runtimeDebugging/freeOSMemory.js"
        - lang: "python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/debug/runtimeDebugging/freeOSMemory.py"

components:
  schemas:
    FreeOSMemoryReq:
      type: object
      required:
        - method
      properties:
        method:
          type: string
          default: 'debug_freeOSMemory'

    FreeOSMemoryResp:
      type: object
      properties:
        result:
            type: string
            example: null     


