openapi: "3.0.2"
info:
  title: Klay Open API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /eth/gasPrice:
    post:
      summary: "[Configuration] eth_gasPrice"
      tags:
        - eth
      operationId: gasPrice
      description: |
        Returns the current price per gas in peb.

        **NOTE:** This API has different behavior from Ethereum's and returns a gas price of Klaytn instead of suggesting a gas price as in Ethereum.

        **JSONRPC:** `eth_gasPrice`

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - type: object
                  properties:
                    method:
                      type: string
                      default: 'eth_gasPrice'

      responses:
        200:
          description: Returns the current price per gas in peb.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/EthGasPriceResp"

      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/eth/config/gasPrice.sh"
        - lang: "java"
          label: "Java"
          source:
            $ref: "../../../code-samples/java/src/main/java/opensdk/sdk/apis/eth/configuration/EthGasPriceExample.java"
        - lang: "javascript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/eth/config/gasPrice.js"
        - lang: "python"
          label: "Python"
          source:
            $ref: "../../../code-samples/python/eth/config/gasPrice.py"

components:
  schemas:
    EthGasPriceResp:
      type: object
      properties:
        result:
          type: string
          format: hex
          description: Integer of the current gas price in peb.
          example: "0xAE9F7BCC00"
